import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { PrimaryNavigation } from './ui/navigation/PrimaryNavigation';
import StoreProvider from './StoreProvider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen flex items-center sm:bg-slate-300`}
      >
        <div className="w-2xl mx-auto p-6 bg-white rounded-lg sm:shadow">
          <PrimaryNavigation />
          <StoreProvider>{children}</StoreProvider>
        </div>
      </body>
    </html>
  );
}
